services:
    cscfa_datagrid.extension:
        class: Cscfa\Bundle\DataGridBundle\Twig\Extension\DatagridExtension
        calls: 
            - [setArguments, [ "%cscfa_datagrid_template%" ]]
        public: false
        tags:
            - { name: twig.extension }
    cscfa_paginator.extension:
        class: Cscfa\Bundle\DataGridBundle\Twig\Extension\PaginatorExtension
        calls: 
            - [setArguments, [ "%cscfa_paginator_template%", "%cscfa_paginator_limit_template%", "@form.factory" ]]
        public: false
        tags:
            - { name: twig.extension }
    cscfa_paginator_form.paginatorLimitForm:
        class: Cscfa\Bundle\DataGridBundle\Form\Type\PaginatorLimit
        tags: 
            - { name: form.type, alias: paginatorLimit }
